version: 0.2

env:
  variables:
    DOCKER_HUB_USERNAME: jeshan
  parameter-store:
    DOCKER_HUB_PASSWORD: /CodeBuild/dockerhub-password
    TWINE_USERNAME: /CodeBuild/pypi-user
    TWINE_PASSWORD: /CodeBuild/pypi-password
    GITHUB_TOKEN: /CodeBuild/GITHUB_TOKEN

phases:
  build:
    commands:
      - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
      - docker-compose run -e TWINE_USERNAME=$TWINE_USERNAME -e TWINE_PASSWORD=$TWINE_PASSWORD -e GITHUB_TOKEN=$GITHUB_TOKEN release
