version: 0.2

phases:
  build:
    commands:
      - pip install pytest boto3 setuptools wheel twine
      - cp setup.py README.md release.sh botostubs/
      - mkdir botostubs/botostubs
      - export AWS_ACCESS_KEY_ID=FAKE AWS_SECRET_ACCESS_KEY=FAKE && time python main.py > botostubs/botostubs/__init__.py
      - /app/botostubs/release.sh
