version: 0.2

env:
  parameter-store:
    TWINE_USERNAME: /CodeBuild/pypi-user
    TWINE_PASSWORD: /CodeBuild/pypi-password
    GITHUB_TOKEN: /CodeBuild/GITHUB_TOKEN

phases:
  build:
    commands:
      - docker-compose run -e TWINE_USERNAME=$TWINE_USERNAME -e TWINE_PASSWORD=$TWINE_PASSWORD -e GITHUB_TOKEN=$GITHUB_TOKEN release
